on: issue_comment

jobs:
  pyrobench:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Pyrobench
        uses: grafana/pyrobench@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go_version: 1.21
